apiVersion: v1
kind: Service
metadata:
  name: game-hub-service
spec:
  selector:
    app: game-hub
  ports:
    - protocol: TCP
      port: 3400         # External port
      targetPort: 3500   # Port your application listens on inside the container
      nodePort: 31510    # Optional: Specify if you want a specific nodePort assigned
  type: NodePort         # Expose service outside the cluster